version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  
  pre_build:
    commands:
      - echo Pre-build started on `date`
  
  build:
    commands:
      - echo Build started on `date`
      - echo "Building..."
  
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
